apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-backstage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: backstage-secret
  annotations:
    kubernetes.io/service-account.name: my-backstage