argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: true
  server:
    ingress:
      enabled: false
      hostname: 'argo-ui.local'
    extraArgs:
      - --insecure
  configs:
    rbac:
      policy.csv: |
        g, system:cluster-admins, role:admin
        g, cluster-admins, role:admin
      policy.default: ''
      scopes: '[groups]'
    cm:
      resource.customizations.health.PersistentVolumeClaim: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Pending" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
            if obj.status.phase == "Bound" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for PVC"
        return hs