apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
  labels:
    app.kubernetes.io/name: tekton
spec:
  destination:
    namespace: tekton-pipelines
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://manifests
    targetRevision: HEAD
    path: "v0.60"
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true