name: Test YQ

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IDPBUILDER_VERSION: v0.4.1
  YQ_VERSION: v4.44.1
  QUAY_ORG: snowdrop

jobs:
  setup-idp:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains( github.event.head_commit.message, 'yq') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/$YQ_VERSION/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Configure app-config.local.yaml file
        run: |
          cat <<EOF > app-config.local.yaml
          app:
            baseUrl: #changeme
          backend:
            baseUrl: #changeme
            cors:
              origin: #changeme
          EOF
          cat app-config.local.yaml

      - name: Override URLs
        uses: mikefarah/yq@v4
        cmd: yq -i '.app.baseUrl = "http://localhost:3000"' app-config.local.yaml; yq -i '.backend.baseUrl = "http://localhost:7007"' app-config.local.yaml; yq -i '.backend.cors.origin = "http://localhost:7007"' app-config.local.yaml

      - name: Override backstage URLs
        run: |
          cat app-config.local.yaml