name: Deploy Standalone OpenShift 4 Cluster

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  openshift-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up CRC
        uses: crc-org/crc-github-action@v1
        with:
          pull-secret: ${{ secrets.OPENSHIFT_PULL_SECRET }}
          preset: openshift/microshift
          #memory: <In MiB, if you want to change from default>
          #cpus: < int, if you want to change from default>
          #disk: <In GiB, if you want to change from default>