name: Test bars, secrets

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  REGISTRY_ORG_VAR: ${{ vars.QUAY_ORG }}
  REGISTRY_ORG_SECRET: ${{ secrets.QUAY_ORG }}

jobs:
  display-variables:
    name: show-variables-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Use variables
        run: |
          echo "repository variable : $REPOSITORY_VAR"
          echo "organization variable : $ORGANIZATION_VAR"
          echo "overridden variable : $OVERRIDE_VAR"
          
          echo "variable from shell environment : $env_var"
          
          echo "Registry org variable: $REGISTRY_ORG_VAR"
          echo "Registry org secret: $REGISTRY_ORG_SECRET"
        env:
          REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
          ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
          OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}
