name: Install IDP and pull/push to gitea

on:
  workflow_dispatch:

env:
  IDPBUILDER_VERSION: v0.6.0

jobs:
  setup-idp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install idpbuilder
        run: |
          version=${IDPBUILDER_VERSION}
          curl -L -o ./idpbuilder.tar.gz "https://github.com/cnoe-io/idpbuilder/releases/download/${version}/idpbuilder-$(uname | awk '{print tolower($0)}')-$(uname -m | sed 's/x86_64/amd64/').tar.gz"
          tar xzf idpbuilder.tar.gz
          sudo mv ./idpbuilder /usr/local/bin/

          idpbuilder version

      - name: Install podman
        run: |
          sudo apt-get -y install podman

      - name: Create an IDP cluster
        run: |
          idpbuilder create

      - name: Get gitea env vars
        run: |
          GITEA_REGISTRY=$(kubectl get ingress/my-gitea -n gitea -ojson | jq -r '.spec.rules[0].host')
          GITEA_USERNAME=$(idpbuilder get secrets -p gitea -ojson | jq -r '.[].data.username')
          GITEA_PASSWORD=$(idpbuilder get secrets -p gitea -ojson | jq -r '.[].data.password')
          
          echo "GITEA_REGISTRY=$GITEA_REGISTRY:8443" >> "$GITHUB_ENV"
          echo "GITEA_USERNAME=$GITEA_USERNAME" >> "$GITHUB_ENV"
          echo "GITEA_PASSWORD=$GITEA_PASSWORD" >> "$GITHUB_ENV"

      - name: Push to gitea using podman
        run: |
          REGISTRY="gitea.cnoe.localtest.me:8443/giteaadmin"
          podman login --tls-verify=false --authfile=${HOME}/.docker/config.json \
            -u $GITEA_USERNAME \
            -p $GITEA_PASSWORD \
            $GITEA_REGISTRY
          podman pull alpine
          podman tag alpine:latest $REGISTRY/alpine:latest
          podman push --tls-verify=false --authfile=${HOME}/.docker/config.json \
            $REGISTRY/alpine:latest

      - name: Push to gitea using docker
        run: |
          REGISTRY="gitea.cnoe.localtest.me:8443/giteaadmin"
          docker login
            -u $GITEA_USERNAME \
            -p $GITEA_PASSWORD \
            $GITEA_REGISTRY
          docker pull alpine
          docker tag alpine:latest $REGISTRY/alpine:latest
          docker push
            $REGISTRY/alpine:latest