name: Create an IDP cluster

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IDPBUILDER_VERSION: v0.4.1

  ARGOCD_VERSION: v0.10.0
  GITEA_VERSION: 1.22.0

  QUAY_ORG: snowdrop

jobs:
  idp-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains( github.event.head_commit.message, 'idp') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install idpbuilder
        run: |
          #version=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/cnoe-io/idpbuilder/releases/latest)
          #version=${version##*/}
          version=${IDPBUILDER_VERSION}
          curl -L -o ./idpbuilder.tar.gz "https://github.com/cnoe-io/idpbuilder/releases/download/${version}/idpbuilder-$(uname | awk '{print tolower($0)}')-$(uname -m | sed 's/x86_64/amd64/').tar.gz"
          tar xzf idpbuilder.tar.gz
          
          ./idpbuilder version
          
          sudo mv ./idpbuilder /usr/local/bin/

      - name: Create an IDP cluster
        run: |    
          idpbuilder create

      - name: Get credentials
        run: |
          idpbuilder get secrets

      - name: Install Argocd client and logon
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64
          
          ARGO_PASSWORD=$(kubectl get secret/argocd-initial-admin-secret -n argocd -ojson | jq -r '.data.password' | base64 -d)
          ARGO_USERNAME=admin
          ARGO_SERVER=argocd.cnoe.localtest.me:8443
          argocd --insecure login $ARGO_SERVER --username $ARGO_USERNAME --password $ARGO_PASSWORD
          
          echo "$ARGO_SERVER=argocd.cnoe.localtest.me:8443" >> "$GITHUB_ENV"

      - name: Create an Argo Application to deploy Tekton
        run: |
          argocd app create tekton \
            --repo https://github.com/tektoncd/pipeline.git \
            --revision v0.59.0 \
            --path config \
            --directory-recurse \
            --insecure \
            --server $ARGO_SERVER \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace tekton \
            --sync-policy auto

      - name: List Argo Application ...
        run: |
          argocd app list