name: Create a kind cluster, install kubevirt to test it

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  KUBEVIRT_VERSION: v1.2.1
  KUBEVIRT_CDI_VERSION: v1.59.0

  KUBEVIRT_TEKTON_TASKS: v0.16.0
  TEKTON_VERSION: v0.59.0
  TEKTON_CLIENT: 0.37.0

  OLM_VERSION: v0.28.0

  QUAY_ORG: snowdrop

jobs:
  kubevirt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create kind cluster
        run: |
          kind create cluster

      - name: Log OS, kube tools, container versions
        run: |
          echo "########### OS ###########"
          cat /etc/os-release
          
          echo "########### Kind version ###########"
          kind --version
          
          echo "########### Docker version ###########"
          docker -v
          
          echo "########### kubectl version ###########"
          kubectl version --client
          
          echo "########### Kubevirt version: $KUBEVIRT_VERSION ###########"
      - name: Install OLM
        run: |
          curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/$OLM_VERSION/install.sh -o install.sh
          chmod +x install.sh
          ./install.sh $OLM_VERSION
      - name : Install Tekton
        run: |
          kubectl create -f https://operatorhub.io/install/tektoncd-operator.yaml
          kubectl apply -f https://raw.githubusercontent.com/ch007m/test-github-action/main/.github/resources/tekton/tektonpipeline.yaml.yaml

      - name: Install and configure ArgoCD
        run: |
          # kubectl create namespace argocd
          # 
          # cat <<EOF | kubectl apply -n olm -f -
          # apiVersion: operators.coreos.com/v1alpha1
          # kind: CatalogSource
          # metadata:
          #   name: argocd-catalog
          # spec:
          #   sourceType: grpc
          #   # Version v0.10.0
          #   image: quay.io/argoprojlabs/argocd-operator-registry@sha256:3f2951534266bc986600601e4bb95812d60342b274e59e58c123f8ef2f07e68b
          #   displayName: Argo CD Operators
          #   publisher: Argo CD Community
          # EOF
          # 
          # kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-operator/master/deploy/operator_group.yaml
          # kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-operator/master/deploy/subscription.yaml
          
          kubectl apply -f https://raw.githubusercontent.com/ch007m/test-github-action/main/.github/resources/argocd/subscription.yaml
          kubectl create ns gitops
          kubectl apply -n gitops -f https://raw.githubusercontent.com/ch007m/test-github-action/main/.github/resources/argocd/argocd.yaml

      - name: Check pods ...
        run: |
          kubectl get po -A
          sleep 30
          kubectl get po -A
          sleep 30