name: macos-runner-podman

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: macos-15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install podman
        run: |
          brew install podman
          brew tap cfergeau/crc
          brew install vfkit
          
          podman -v
          vfkit -v
          /opt/homebrew/Cellar/podman/5.3.1/libexec/podman/vfkit
          
          podman machine init
          
          podman machine start --log-level debug