name: macos-runner-podman

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: macos-15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install podman
        run: |
          brew install podman
          podman -v
          
          podman machine init
          
          vfkit -v
          
          podman machine start --log-level debug