name: macos-runner-podman

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: macos-13
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install podman
        run: |
          brew install podman
          # not needed as podman is installing it
          #brew tap cfergeau/crc
          #brew install vfkit
          
          podman -v
          /opt/homebrew/Cellar/podman/5.3.1/libexec/podman/vfkit -v
          
          podman machine init
          podman machine start --log-level debug
