name: Node version env var

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  templating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: "${NODE_VERSION}"