name: Requesting the JWT using the Actions core toolkit

on:
  workflow_dispatch:

jobs:
  job:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: 'https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token'
        with:
          script: |
            # Won't work as: SyntaxError: Invalid or unexpected token
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)