name: ubuntu-homebrew-podman

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install podman
        run: |
          brew install podman
          brew install crun
          brew services start podman
      - name: Display versions    
          podman -v
          crun -v
        
          podman info

      - name: Run container
        run: |
          podman --log-level debug run -it -p 8888:8888 nginxdemos/nginx-hello:plain-text   
          
