name: ubuntu-homebrew-podman

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Remove old executables
        run: |
          # Remove this old crun executable to let brew to install a newer one ...
          sudo apt-get remove crun

      - name: Install podman and show dependencies
        run: |
          # What brew will install: https://ghcr.io/v2/homebrew/core/podman/manifests/5.3.1_1
          brew install podman
          brew services start podman
          
          brew deps --tree --installed podman

      - name: Display versions
        run: |
          podman -v
          crun -v
        
          podman info

      - name: Run container
        run: |
          podman --log-level debug run -it -p 8888:8888 nginxdemos/nginx-hello:plain-text   
          
