name: Podman cli

on:
  workflow_dispatch:

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      #- name: Emulate Docker CLI with Podman
      #  uses: k8s-crafts/podman-cli-action@v1
        #with:
        #  podman_api: true

      - name: Test podman cli
        run: |
          apt-get update
          apt-get -y install podman
          apt-get -y install socat
          
          systemctl --user enable --now podman.socket
          
          #echo "## DOCKER HOST: "
          #export DOCKER_HOST="unix:///run/user/$(id -u)/podman/podman.sock"
          
          echo "## Launching socat..."
          socat TCP-LISTEN:2376,reuseaddr,fork,bind=0.0.0.0 unix:///run/user/$(id -u)/podman/podman.sock &
          
          echo "## Podman version"
          podman -v
          
          echo "### Install pack ###"
          PACK_CLI_VERSION="v0.35.1"
          TEMP_DIR="./tmp"
          USER_BIN_DIR="./bin"
          
          mkdir -p $TEMP_DIR
          mkdir -p $USER_BIN_DIR
  
          curl -sSL "https://github.com/buildpacks/pack/releases/download/${PACK_CLI_VERSION}/pack-${PACK_CLI_VERSION}-linux.tgz" | tar -C ${TEMP_DIR} --no-same-owner -xzv pack
          mv ${TEMP_DIR}/pack ${USER_BIN_DIR}

          echo "### Pack version ###"
          $USER_BIN_DIR/pack --version
          $USER_BIN_DIR/pack config experimental true
          
          git clone https://github.com/buildpacks/samples
          export DOCKER_HOST="tcp://127.0.0.1:2376"
          $USER_BIN_DIR/pack build sample-app --path samples/apps/java-maven --builder cnbs/sample-builder:jammy --docker-host inherit -v