name: macos-runner-podman

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: macos-13
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install podman
        run: |
          brew install podman
          
          # It is not needed to install vfkit since podman >= 14 as already packaged
          brew tap cfergeau/crc
          brew install vfkit
          
          podman -v
          
          podman machine init
          podman machine start --log-level debug
          
          podman machine ssh "cat /etc/redhat-release"
          
          podman run -it -p 8888:8888 nginxdemos/nginx-hello:plain-text          
          
