# Github workflow
# https://stackoverflow.com/questions/74949299/how-to-versioning-releases-in-github-actions
# https://stackoverflow.com/questions/66017161/add-a-tag-to-a-docker-image-if-theres-a-git-tag-using-github-action
# To generate the docker labels/tags --> https://github.com/docker/metadata-action
# Updating helm chart version
# - name: Update Chart Version
#   run: |
#     # Replace the AppVersion in the Chart.yaml file with the release tag name
#     NEW_VERSION="${GITHUB_REF#refs/tags/}"
#     helm show chart ./path/to/your/helm/chart > ./chart-temp.yaml
#     yq eval ".version.appVersion = \"$NEW_VERSION\"" -i ./chart-temp.yaml
#     mv ./chart-temp.yaml ./path/to/your/helm/chart/Chart.yaml
#
#     git config user.email "github-actions@github.com"
#     git config user.name "GitHub Actions"
#     git add ./path/to/your/helm/chart/Chart.yaml
#     git commit -m "Update Helm chart version to $NEW_VERSION"
#     git push

name: Tag Docker Image like the chart AppVersion

on:
  workflow_dispatch:
  push:
    tags: [ v* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: snowdrop/godaddy-webhook

      - uses: azure/setup-helm@v3

      - name: Tag chart and image
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
        run: |
          echo "This is event referenced as : ${{ github.ref_type }}."
          echo "Tag Name: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          
          export NEW_VERSION="${{ github.ref_name }}"
          echo "New version: $NEW_VERSION"
          helm show chart ./deploy/charts/godaddy-webhook > ./chart-temp.yaml
          
          if ! command -v yq &> /dev/null
          then
            echo "yq could not be found"
          fi
  
          yq '.appVersion = env(NEW_VERSION)' -i ./chart-temp.yaml
          
          echo "Chart updated"
          cat ./deploy/charts/godaddy-webhook/Chart.yaml

      - name: Don't tag chart and image
        if: ${{ github.ref_type != 'tag' }}
        run: |
          echo "This is event referenced as : ${{ github.ref_type }}."
          echo "Commit SHA: ${{ github.sha }}"