# Github workflow
# https://stackoverflow.com/questions/74949299/how-to-versioning-releases-in-github-actions
# https://stackoverflow.com/questions/66017161/add-a-tag-to-a-docker-image-if-theres-a-git-tag-using-github-action
# To generate the docker labels/tags --> https://github.com/docker/metadata-action

name: Tag Docker Image like the chart AppVersion

on:
  workflow_dispatch:
  push:
    tags: [ v* ]

jobs:
  test-next-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for github-action-get-previous-tag

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: next-version
        with:
          scheme: semver
          increment: minor

      - name: Create release
        id: create_release_id
        run: |
          echo ${{ steps.semver.next-version.version }}
          echo ${{ steps.semver.next-version.v_version }}
          echo ${{ steps.semver.next-version.major_version }}
          echo ${{ steps.semver.next-version.minor_version }}
          echo ${{ steps.semver.next-version.patch_version }}
          echo ${{ steps.semver.next-version.major_v_version }}
          echo ${{ steps.semver.next-version.minor_v_version }}
          echo ${{ steps.semver.next-version.patch_v_version }}
        # uses: actions/create-release@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   tag_name: ${{ steps.next-version.outputs.version }}
        #   release_name: Release ${{ steps.semver.next-version.version }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: snowdrop/godaddy-webhook

      - uses: azure/setup-helm@v3

      - name: Tag chart and image
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
        run: |
          echo "This is event referenced as : ${{ github.ref_type }}."
          echo "Tag Name: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          
          TAG_VERSION="${{ github.ref_name }}"
          export NEW_VERSION="${TAG_VERSION:1}"
          echo "New version: $NEW_VERSION"
  
          yq '.appVersion = env(NEW_VERSION)' -i ./deploy/charts/godaddy-webhook/Chart.yaml
          yq '.image.tag  = env(NEW_VERSION)' -i ./deploy/charts/godaddy-webhook/values.yaml
          
          echo "Chart updated"
          cat ./deploy/charts/godaddy-webhook/Chart.yaml
          
          echo "Values updated"
          cat ./deploy/charts/godaddy-webhook/values.yaml

      - name: Don't tag chart and image
        if: ${{ github.ref_type != 'tag' }}
        run: |
          echo "This is event referenced as : ${{ github.ref_type }}."
          echo "Commit SHA: ${{ github.sha }}"