name: test shared matrix
on:
  push:
    branches:
      - main

jobs:
  builder:
    name: set matrix
    strategy:
      matrix:
        cfg:
          - { builder-image: "paketobuildpacks/builder-jammy-tiny:0.0.175" }
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        env:
          CFG: ${{ toJSON(matrix.cfg) }}
        run: jq -r -n 'env.CFG | fromjson | @json "::set-output name=result::\(.data)"'

  runner:
    needs: [ builder ]
    strategy:
      matrix:
        cfg: ${{ fromJson(needs.builder.outputs.matrix) }}
    steps:
      - run: |
          echo  "Builder-image: ${{ matrix.cfg.builder-image }}"