name: Tag reference

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true
  push:
    tags: [ v* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Tag chart and image
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
        run: |
          echo "This is event referenced as : ${{ github.ref_type }}."
          TAG_NAME="${{ github.ref_name }}"
          echo "Tag Name: ${TAG_NAME:1}"
          echo "Commit SHA: ${{ github.sha }}"
