name: Template

on:
  workflow_dispatch:

jobs:
  templating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Render template
        id: render_template
        uses: chuhlomin/render-template@v1
        env:
         VM_IMAGES_NAMESPACE: TOTO
        with:
          template: .github/resources/templates/quarkus-dev-virtualmachine.tmpl
          vars: |
            vmImagesNamespace: ${{ env.VM_IMAGES_NAMESPACE }}

      - name: Deploy
        run: |-
            echo '${{ steps.render_template.outputs.result }}'
      #- uses: release-engineers/action-template@v2
      #  env:
      #    VM_IMAGES_NAMESPACE: TOTO
      #  with:
      #    source: '.github/resources/templates/quarkus-dev-virtualmachine.tmpl'
      #    target: 'quarkus-dev-virtualmachine.yaml'

      #- shell: bash
      #  run: |
      #    echo "### Check the generated file"
      #    cat quarkus-dev-virtualmachine.yaml