name: Shared Matrix Example

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          # Syntax is working
          # echo 'matrix={"include":[{"project":"foo","config":"Debug"},{"project":"bar","config":"Release"}]}' >> $GITHUB_OUTPUT
          
          # This syntax reports a : A mapping was not expected
          echo 'params={"builder-image":"paketobuildpacks/builder-jammy-tiny:0.0.175","pack_cli_version":"v0.30.0-rc1"}' >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.mymatrix) }}
    steps:
      - run: |
          echo "Builder image: ${{ matrix.params.builder-image }}"
          echo "Pack client image: ${{ matrix.params.pack_cli_version }}"