name: Shared Matrix Example

on: [push]

jobs:
  use-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Show Matrix Info
        run: |
          echo "Matrix YAML:"
          cat <<EOF > matrix.yml
          matrix:
            include:
              - os: ubuntu-latest
                node_version: "14"
              - os: ubuntu-latest
                node_version: "16"'
          EOF

      - name: Use Matrix in Another Job
        id: use-matrix
        run: |
          echo "Matrix in YAML:"
          cat matrix.yml
          echo "MATRIX=$(cat matrix.yml)" >> $GITHUB_ENV
        shell: /usr/bin/bash -e {0}

  print-matrix:
    needs: use-matrix
    runs-on: ubuntu-latest

    steps:
      - name: Print Matrix Values
        run: |
          echo "MATRIX from Environment: $MATRIX"