name: Shared Matrix Example

on: [push]

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          # Syntax is working
          # echo 'matrix={"include":[{"project":"foo","config":"Debug"},{"project":"bar","config":"Release"}]}' >> $GITHUB_OUTPUT
          
          # This syntax reports a : A mapping was not expected
          #echo 'params={"builder-image":"paketobuildpacks/builder-jammy-tiny:0.0.175","pack_cli_version":"v0.30.0-rc1"}' >> $GITHUB_OUTPUT
          echo "matrix=$(jq -c . < ./matrix.json)" >> $GITHUB_OUTPUT

  job1:
    needs: configure
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.configure.outputs.matrix) }}
    steps:
      - run: |
          echo "Builder image: ${{ matrix.builder-image }}"
          echo "Pack client image: ${{ matrix.pack_cli_version }}"